### ISSUE TITLE
Shortcode ohne Parameter

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-synonym#1]
Wenn beim Shortcode kein Parameter angegeben wird, sollte per Default eine Tabelle erstellt werden mit allen Synonymen.

Aktuell kommt als Ergebnis eine Zahl?

**Comment by thenickless** [comment]
umgebendes DIV wie bei rrze-faq

-> Tabelle betraf eine Version vor 2.0.0
